language: java

dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8
  - openjdk8

before_script:
  - cd ./wiki

before_deploy:
  - git config --local user.name "Sergey Nesterov"
  - git config --local user.email "menestrel.me@gmail.com"
  - git describe --tags --contains || git tag "latest"

jobs:
  include:
    - stage: GitHub Release
      script: mvn package -DskipTests
      deploy:
        provider: releases
        api_key:
          secure: cX+VwnhwoeJkia/JFyzc42HxQ0SH5CHSxQMPb6bAW4QeuzB0qjpHDWdjfGysQg4cRhK7BUPJO+duzbmpXiRNlsbHsAquJrOxBsFSZYcdN3hjG6+Fm5r2xm7eOoDFN7fA2OVWMEan9u19jv8Wgv1K4P0nDjco4PX+xAQildgMwWuK0vrpL7cL7KaUqLlJnXzmJWHa5J8woEpKJKmv8cSW/0n+/3GQDVGgAiyns/2aQSqjmf+UfMgZqVVQv2FRh6/qS5FzcG5ukRwtTfnAk4akWolvw1EDfA/CmruBplVhQzMVbxz7izOSsm8axTRcbNHZgkuNaNcEKJ5O7/DA8IfU+k/DXey6RHZ3fMG34G15xILqBYytDu+dJlYsoA5/aSt+pfNKOPIcKcIifi3+Lkfzfx7YFp3ie06nPk3H21oze/yfE7+AsYXIfPV9NySpSAEHdmaZvlh9Mw0Fvg4aB3QkdP9uxFAMS9RHA+pX/tSo94XgTkXwvUDmnBZHz4HyISB0mozilnqXUsmlvNXdBkk7h5pxyomagevx/Gq/nw+AuzTXU8Xc61SESiUiZkJW/+K48Xu/rOXqXHE0iSa8ITOClpZKcDxQiggP2C0fELpkM5Cd3k9Hf3J3tGK3F9GzokolWBzvSqAhIA04Z0DKJ+f29hdBwy4wwih/TDDzRe8Xaxg=
        file_glob: true
        file: ./**/*.war
        skip_cleanup: true
        on:
          tags: true
          branch: master
    - stage: GitHub Release
      script: mvn package -DskipTests
      deploy:
        provider: releases
        api_key:
          secure: cX+VwnhwoeJkia/JFyzc42HxQ0SH5CHSxQMPb6bAW4QeuzB0qjpHDWdjfGysQg4cRhK7BUPJO+duzbmpXiRNlsbHsAquJrOxBsFSZYcdN3hjG6+Fm5r2xm7eOoDFN7fA2OVWMEan9u19jv8Wgv1K4P0nDjco4PX+xAQildgMwWuK0vrpL7cL7KaUqLlJnXzmJWHa5J8woEpKJKmv8cSW/0n+/3GQDVGgAiyns/2aQSqjmf+UfMgZqVVQv2FRh6/qS5FzcG5ukRwtTfnAk4akWolvw1EDfA/CmruBplVhQzMVbxz7izOSsm8axTRcbNHZgkuNaNcEKJ5O7/DA8IfU+k/DXey6RHZ3fMG34G15xILqBYytDu+dJlYsoA5/aSt+pfNKOPIcKcIifi3+Lkfzfx7YFp3ie06nPk3H21oze/yfE7+AsYXIfPV9NySpSAEHdmaZvlh9Mw0Fvg4aB3QkdP9uxFAMS9RHA+pX/tSo94XgTkXwvUDmnBZHz4HyISB0mozilnqXUsmlvNXdBkk7h5pxyomagevx/Gq/nw+AuzTXU8Xc61SESiUiZkJW/+K48Xu/rOXqXHE0iSa8ITOClpZKcDxQiggP2C0fELpkM5Cd3k9Hf3J3tGK3F9GzokolWBzvSqAhIA04Z0DKJ+f29hdBwy4wwih/TDDzRe8Xaxg=
        file_glob: true
        file: ./**/*.war
        overwrite: true
        skip_cleanup: true
        on:
          tags: false
          branch: master
