language: java

dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8
  - openjdk8

before_script:
  - cd ./wiki

before_deploy:
  - git config --local user.name "Sergey Nesterov"
  - git config --local user.email "menestrel.me@gmail.com"
  - git describe --tags --contains || git tag "latest"

jobs:
  include:
    - stage: GitHub Release
      script: mvn package -DskipTests
      deploy:
        provider: releases
        api_key:
          secure: GuBlws/MtDWk8sk2KgKrCN00tcrzVzT4t5PTrt8+0vvhJzRKFzCDvchy643WOLOnVGvkTy52qc7kYwLZHTYk8Ir8Mp2YRPBtpDkgfsywqAcB9OJ2t9TSJZOExDeBYvkWZhE9RUDnecC5lGHMt4WFd8shX/ehGSSjG+QzEyEC//NRg3ZnZlZL8JVVB/Q37hwgiEmSHoo/9okK6hizzRtXnmGOO7ZT2//Bzx029YI52tLZwdqz8hoN5Yv+nuIRNA7aQnGLNHPAJAUD6rutI2MIz7x11RSOah4awRhTJi/7OsSZRgYwqNXZ+xy1AiUsLKNK+FTGiNwMkVrgrJm7/fVzjSnQO2vPQiVHBD94cRYB+T/DFtQDUwtMvUq932xqElftZKjzjUfMo0zl6qYBOpGjQ1cb+ZdlIgYlBIENMgeuBoroVO3+H1csveah/cq+Ipw0X1CVcBooy5Zk+5wxq/xKPqImBtnfgiPy6N8tsDT+HjoL3if5MctHF4FEihqIaO52TxML3lL6h3UjxkqXdBOYyYYesMgBkFrC2LTkYcFcCmG5D10afPYXH69Qu12jJ8O9u1pfTslESEGvIOnwVEUp2diLpgDbHd+i2TpwSjNm0PWmQdEsdUhvm17ayNPFETEqUDcsMJjNJv3euNijx+spHxtGynzLr/GrL0xtNrxUszU=
        file_glob: true
        file: ./**/*.war
        skip_cleanup: true
        on:
          tags: true
          branch: master
    - stage: GitHub Release
      script: mvn package -DskipTests
      deploy:
        provider: releases
        api_key:
          secure: GuBlws/MtDWk8sk2KgKrCN00tcrzVzT4t5PTrt8+0vvhJzRKFzCDvchy643WOLOnVGvkTy52qc7kYwLZHTYk8Ir8Mp2YRPBtpDkgfsywqAcB9OJ2t9TSJZOExDeBYvkWZhE9RUDnecC5lGHMt4WFd8shX/ehGSSjG+QzEyEC//NRg3ZnZlZL8JVVB/Q37hwgiEmSHoo/9okK6hizzRtXnmGOO7ZT2//Bzx029YI52tLZwdqz8hoN5Yv+nuIRNA7aQnGLNHPAJAUD6rutI2MIz7x11RSOah4awRhTJi/7OsSZRgYwqNXZ+xy1AiUsLKNK+FTGiNwMkVrgrJm7/fVzjSnQO2vPQiVHBD94cRYB+T/DFtQDUwtMvUq932xqElftZKjzjUfMo0zl6qYBOpGjQ1cb+ZdlIgYlBIENMgeuBoroVO3+H1csveah/cq+Ipw0X1CVcBooy5Zk+5wxq/xKPqImBtnfgiPy6N8tsDT+HjoL3if5MctHF4FEihqIaO52TxML3lL6h3UjxkqXdBOYyYYesMgBkFrC2LTkYcFcCmG5D10afPYXH69Qu12jJ8O9u1pfTslESEGvIOnwVEUp2diLpgDbHd+i2TpwSjNm0PWmQdEsdUhvm17ayNPFETEqUDcsMJjNJv3euNijx+spHxtGynzLr/GrL0xtNrxUszU=
        file_glob: true
        file: ./**/*.war
        overwrite: true
        skip_cleanup: true
        on:
          tags: false
          branch: master
