language: java

dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8
  - openjdk8

before_script:
  - cd ./wiki

before_deploy:
  - git config --local user.name "sergeynesterov"
  - git config --local user.email "menestrel.me@gmail.com"
  - git describe --tags --contains || git tag "latest"

jobs:
  include:
    - stage: GitHub Release
      script: mvn package -DskipTests
      deploy:
        provider: releases
        api_key:
          secure: "P2w7+gTC5NnS40gMtu5E2m3snK6yvPXfpL2GTJdcnyOjnSSkoFWQKi9tAblFnpDjlVAlqoTrQfSknk5/60q4QRhBWQi34nBA+Hm4+I3tRcyiHziT8DpVisNWaBg/Nnhd/5siaigq53RwysWzW4LfQkh9C3IiqzCFJQ5pPinTcXaAzSD2lO2ipEuGzS31PVlq3P72ZydS124dVWC2Sfd9CPU5ceNRC/QPXD3jShlOUNg7pOW4XAxJDKAOkHHZgE5WhQNcWv0Ns+bsYReWDRFkpm/8q4f1+smdh8cmJm1qbQmWmG/2kxXSSboKpBj3nk2Zcl6kn3x6CAo+bAikwV1pJ6UPj4Q7RAes2Wf1saj+AaE7soarG7zEMUeiMNWdCDhmU//WLY08Rwy4lWHVoORgIsXG1u3NLpZ3FXzeumEQr1TPUo4n7pAP7rYflyEwLrMh1fuWmM+b3BxN79NqinAX9xPYRnmmgpwaHvO6wydyHLVQNLNyFEYhy+G52peXoSkww/9bzjmKB6zEbJlb8XPs+JLDkA57GZXofwcJgr2hyibxAmKxUmyFG5yeyRDcFy+lMuVGnBEK6nNdOiBIqOxfoE5xQ2nAIYIO9dzanLi79AZ64ZwIFZW2Gbrf0XGa9zzqmEdyn15xzFUD3vYzg7/gMBqz+Kkb2Y4O5L7WfUX6Y6s="
        file_glob: true
        file: ./**/*.war
        skip_cleanup: true
        on:
          tags: true
          branch: master
    - stage: GitHub Release
      script: mvn package -DskipTests
      deploy:
        provider: releases
        api_key:
          secure: "P2w7+gTC5NnS40gMtu5E2m3snK6yvPXfpL2GTJdcnyOjnSSkoFWQKi9tAblFnpDjlVAlqoTrQfSknk5/60q4QRhBWQi34nBA+Hm4+I3tRcyiHziT8DpVisNWaBg/Nnhd/5siaigq53RwysWzW4LfQkh9C3IiqzCFJQ5pPinTcXaAzSD2lO2ipEuGzS31PVlq3P72ZydS124dVWC2Sfd9CPU5ceNRC/QPXD3jShlOUNg7pOW4XAxJDKAOkHHZgE5WhQNcWv0Ns+bsYReWDRFkpm/8q4f1+smdh8cmJm1qbQmWmG/2kxXSSboKpBj3nk2Zcl6kn3x6CAo+bAikwV1pJ6UPj4Q7RAes2Wf1saj+AaE7soarG7zEMUeiMNWdCDhmU//WLY08Rwy4lWHVoORgIsXG1u3NLpZ3FXzeumEQr1TPUo4n7pAP7rYflyEwLrMh1fuWmM+b3BxN79NqinAX9xPYRnmmgpwaHvO6wydyHLVQNLNyFEYhy+G52peXoSkww/9bzjmKB6zEbJlb8XPs+JLDkA57GZXofwcJgr2hyibxAmKxUmyFG5yeyRDcFy+lMuVGnBEK6nNdOiBIqOxfoE5xQ2nAIYIO9dzanLi79AZ64ZwIFZW2Gbrf0XGa9zzqmEdyn15xzFUD3vYzg7/gMBqz+Kkb2Y4O5L7WfUX6Y6s="
        file_glob: true
        file: ./**/*.war
        overwrite: true
        skip_cleanup: true
        on:
          tags: false
          branch: master
